In [ ]:
! pip install kaggle

In [ ]:
! mkdir .kaggle


mkdir: cannot create directory ‘.kaggle’: File exists


In [ ]:
! cp kaggle.json ~/.kaggle

In [ ]:
! kaggle datasets download -d lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

 31% 8.00M/25.7M [00:00<00:00, 83.1MB/s]
100% 25.7M/25.7M [00:00<00:00, 126MB/s] 


In [ ]:
! unzip imdb-dataset-of-50k-movie-reviews.zip

Archive:  imdb-dataset-of-50k-movie-reviews.zip
  inflating: IMDB Dataset.csv        


In [ ]:
import pandas as pd


In [ ]:
df = pd.read_csv("IMDB Dataset.csv")

In [ ]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

<h1>Text Cleaning</h1>
<ol>
<li>Sample 10000 rows</li>
<li>Remove html tags</li>
<li>Remove special characters</li>
<li>Converting every thing to lower case</li>
<li>Removing Stop words e.g. the, from, then, etc.</li>
<li>Stemming. i.e. making multiple words with similar meaning into one. e.g. love, loving, loved, lovable, etc</li>
</ol>

In [ ]:
df = df.sample(10000)

In [ ]:
df.shape

(10000, 2)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 23052 to 48444
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB


In [ ]:
df.sentiment.replace({"positive":1, "negative":0}, inplace=True)

In [ ]:
df.head()

review  sentiment
23052  The evil bikie gang in this movie were called ...          0
34517  this movie isn't that great...at all but it's ...          0
34649  Bromwell High is nothing short of brilliant. E...          1
4575   Naturally Sadie is by far the worst show i hav...          0
14526  Fantastic, Madonna at her finest, the film is ...          1

using re library, i.e. regular expressions to remove html tags

In [ ]:
df.iloc[11].review

'To me, this movie was just plain confusing, slow, and uninteresting. Why did the aliens choose to communicate through ants? It makes no sense. The ending was muddled and made no sense whatsoever. In the end, I was hoping that the ants would kill everyone.<br /><br />Avoid this one at all costs. Not even MST3K could save it.'

In [ ]:
import re
clean = re.compile('<.*?>')
re.sub(clean, '', df.iloc[11].review)

'To me, this movie was just plain confusing, slow, and uninteresting. Why did the aliens choose to communicate through ants? It makes no sense. The ending was muddled and made no sense whatsoever. In the end, I was hoping that the ants would kill everyone.Avoid this one at all costs. Not even MST3K could save it.'

In [ ]:
def remove_html(text):
  clean = re.compile('<.*?>')
  return re.sub(clean,'', text)


In [ ]:
df.review = df.review.apply(remove_html)

In [ ]:
def convert_lowerCase(text):
  return text.lower()

In [ ]:
df.review = df.review.apply(convert_lowerCase)

In [ ]:
df.iloc[11].review

'to me, this movie was just plain confusing, slow, and uninteresting. why did the aliens choose to communicate through ants? it makes no sense. the ending was muddled and made no sense whatsoever. in the end, i was hoping that the ants would kill everyone.avoid this one at all costs. not even mst3k could save it.'

In [ ]:
def remove_special(text):
  x =''
  for i in text:
    if  i.isalnum():
      x = x+i
    else:
      x = x+" "
  return x

In [ ]:
remove_special("holla% hy dis @ hi")

'holla  hy dis   hi'

In [ ]:
df.review = df.review.apply(remove_special)

Removing step words
<br> importing nltk
 <br>natural language tool kit

In [ ]:
import nltk

In [ ]:
## e.g.
from nltk.corpus import stopwords

In [ ]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
englstopwords = stopwords.words("english")

In [ ]:
type(englstopwords)

list

In [ ]:
len(englstopwords)

179

In [ ]:
englstopwords[0:20]

In [ ]:
def remove_stopWords(text):
  x = []
  for i in text.split():
    if i not in englstopwords:
      x.append(i)

  y = x[:]
  x.clear()
  return y

In [ ]:
remove_stopWords("i think that this is loveing not how it should be done")

['think', 'loveing', 'done']

In [ ]:
type(df.review)

pandas.core.series.Series

In [ ]:
df.review.iloc[1]

'this movie isn t that great   at all but it s good when you want to just laugh  because it s pretty ridiculous    there are a lot of mistakes in it and it s cheesy  i got this movie for christmas like 5 years ago but for some reason i ve never given it away  i guess i just like it for a rainy day even though i only watch it like once a year  this is a very 90 s movie so it s really funny to see how everyone dresses and acts  this movie is good for someone young   although come to think of it  i didn t even like it much when i was like 12 but that s just my personal opinion  the movie was really predictable  i wish it had had some extra weird twists but i guess it was trying to be an appropriate movie for everyone to enjoy  i think it was appropriate for the whole family but hallie s dress was a bit unmodest but certainly appropriate enough for family material '

In [ ]:
df.review = df.review.apply(remove_stopWords)

In [ ]:
df.head()

review  sentiment
23052  [evil, bikie, gang, movie, called, savages, he...          0
34517  [movie, great, good, want, laugh, pretty, ridi...          0
34649  [bromwell, high, nothing, short, brilliant, ex...          1
4575   [naturally, sadie, far, worst, show, ever, see...          0
14526  [fantastic, madonna, finest, film, funny, acti...          1

In [ ]:
# performing stemming

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
def stemming(text):
  y = []
  for i in text:
    y.append(ps.stem(i))
  z = y[:]
  y.clear()
  return z

In [ ]:
stemming(["i", "loved", "the", "loving"])

['i', 'love', 'the', 'love']

In [ ]:
df.review = df.review.apply(stemming)

In [ ]:
# join back

def join_back(list_input):
  return " ".join(list_input)

In [ ]:
join_back(["i", "am", "vishal", "thakur"])

'i am vishal thakur'

In [ ]:
df.review = df.review.apply(join_back)

In [ ]:
df.groupby(by="sentiment").count()

review
sentiment        
0            4990
1            5010

In [ ]:
# from sklearn.feature_extraction.text import CountVectorizer
# cv = CountVectorizer() # here we can pass an parameter max_feature = 500 or anything else
# # this will tell countvectorizer to take only 500 important words

In [ ]:
# with above configurations, features were 36309
# and scores were
# Gaussian score: 0.6405
# Multi score: 0.8245
# Benoulli score: 0.8175

In [ ]:
# with max_features  = 1000
cv = CountVectorizer(max_features=1000)

In [ ]:
X = cv.fit_transform(df.review).toarray()

In [ ]:
X.shape

(10000, 1000)

In [ ]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [2, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X[X==1]

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
y = df.iloc[:,-1].values

In [ ]:
y.shape

(10000,)

In [ ]:
# X, y 
# Training set
# Test set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.2)

In [ ]:
X_test.shape

(2000, 1000)

In [ ]:
y_test.shape

(2000,)

In [ ]:
X_train.shape

(8000, 1000)

In [ ]:
y_train.shape

(8000,)

In [ ]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [ ]:
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf3 = BernoulliNB()

In [ ]:
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)
clf3.fit(X_train, y_train)

BernoulliNB()

In [ ]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)
y_pred3 = clf3.predict(X_test)

In [ ]:
y_test.shape

(2000,)

In [ ]:
y_pred1.shape

(2000,)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
# # previous scores
# Gaussian score: 0.6405
# Multi score: 0.8245
# Benoulli score: 0.8175

In [ ]:
# as we can see accuracy has increased

In [ ]:
print("Gaussian score:",accuracy_score(y_test, y_pred1))
print("Multi score:",accuracy_score(y_test, y_pred2))
print("Benoulli score:",accuracy_score(y_test, y_pred3))

Gaussian score: 0.77
Multi score: 0.8375
Benoulli score: 0.8405


In [ ]:
import numpy as np


In [ ]:
X_test

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
def what_is_review(text):
  text = remove_html(text)
  text = remove_special(text)
  text = remove_stopWords(text)
  text = stemming(text)
  text = join_back(text)
  text_array = cv.transform([text])
  review = clf3.predict(text_array)
  if review[0] == 1:
    x = "positive"
  else:
    x = "negative"
  return x


In [ ]:
what_is_review("Can you show me a better movie than this")

'negative'

In [ ]:
what_is_review("I don't know how to say things i felt about this movie. I mean before the interval their was so much action and audience in cinema just went hyped after the climax scene")

'negative'